### ISSUE TITLE
Cesium version 1.18+ breaks NaturalEarthII in this branch

### ISSUE THREAD

**Issue by cutlasjgh** [AnalyticalGraphicsInc/cesium-assets#1]
If you use this enhanced asset package for higher detail NaturalEarthII imagery, then you will have issues if you update your Cesium version to 1.18 or more recent, unless you modify the `tilemapresource.xml` file. You might get a load error but probably you will see map textures that just look wrong, due to image being stretched farther Hoizontally than it should (smearing).
Problem is lines 6 and 7, it's an easy fix, you will see what I mean if you diff the 
`cesium/blob/master/Source/Assets/Textures/NaturalEarthII/tilemapresource.xml`
versus the
`cesium-assets/blob/master/imagery/NaturalEarthII/tilemapresource.xml`
files.
So if you are using cesium 1.18 or more recent, you want to probably change lines 6 and 7 of the optional cesium-assets `tilemapresource.xml` to read:
```
       <BoundingBox miny="-90.00000000000000" minx="-180.00000000000000"
maxy="90.00000000000000" maxx="180.00000000000000"/>
       <Origin y="-90.00000000000000" x="-180.00000000000000"/>
```
Which will bring your optional cesium-assets `timemapresource.xml` into line with the cesium version of `tilemapresource.xml` but preserves the level 5 detail of the optional NaturalEarthII imagery.
Reason this asset is broke for new versions of cesium is that it relates to the flipXY issue that was checked into cesium in January 28, 2016 timeframe. 

references: https://github.com/AnalyticalGraphicsInc/cesium/commit/c5061fa5756a4ed1fe2ecde05a8e8de4154f0874

**Comment by pjcozzi** [comment]
Thanks for the report, @cutlasjgh!  @TomPed can you make this update?
