### ISSUE TITLE
Example code for NaturalEarthII is out of date

### ISSUE THREAD

**Issue by trickidicki** [AnalyticalGraphicsInc/cesium-assets#3]
Trying the example code for NaturalEarthII (https://github.com/AnalyticalGraphicsInc/cesium-assets/tree/master/imagery) throws this error:
Uncaught TypeError: Cesium.TileMapServiceImageryProvider is not a constructor

Should be:
```
imageryProvider : new Cesium.createTileMapServiceImageryProvider({
        url : 'assets/Textures/NaturalEarthII/',
        maximumLevel : 2,
        credit : 'Imagery courtesy Natural Earth'
    })
```

**Comment by pjcozzi** [comment]
Thanks for the report, @trickidicki.  This was fixed in #4.
